### PR TITLE
Add info about making dummy PRs.

### PR DESCRIPTION
**Pull request by MaxWilson**
The readme says "Once accepted your work will be published through a rebuild here, so submit a dummy pull request here".

This is a dummy PR for the sake of recently-added Options API documentation (usage examples).

If this dummy PR is not needed to trigger a rebuild, please ignore.

### CODE REVIEW

**Comment by dsyme** [comment]
It is needed, thanks

This line should pick things up from dotnet/fsharp main, all going as planned https://github.com/fsharp/fsharp-core-docs/blob/master/.github/workflows/docs.yml#L29

**Comment by dsyme** [comment]
@MaxWilson Please report here whether results are as hoped after the github action finishes

**Comment by dsyme** [comment]
Action is here: https://github.com/fsharp/fsharp-core-docs/actions/runs/572198701

**Comment by dsyme** [comment]
@MaxWilson Would you like to become co-maintainer on this, so you can trigger at will?  I'd be happy to have that

**Comment by MaxWilson** [comment]
@dsyme sure, I am planning to add documentation for more of the API so that would help.

The results at https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-optionmodule.html look as I was hoping they would. Success!

**Comment by dsyme** [comment]
@MaxWilson Invitation sent!

**Pull request merged**
